config/routes.rb
Rails.application.routes.draw do
  get 'main_page/call_details'

  get 'main_page/agents'

  resources :agents
  resources :call_details
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/agent.rb
class Agent < ApplicationRecord
  belongs_to :call_detail
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/call_detail.rb
class CallDetail < ApplicationRecord
def self.search(temp)
  if (temp[:start_time]) && (temp[:end_time])
    where(["start_time>= :start_time AND end_time<= :end_time",
    {start_time: temp[:start_time], end_time: temp[:end_time]}])    
  else
    all()
  end
end
end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
  before_action :set_agent, only: [:show, :edit, :update, :destroy]

  # GET /agents
  # GET /agents.json
  def index
    @agents = Agent.all
  end

  # GET /agents/1
  # GET /agents/1.json
  def show
  end

  # GET /agents/new
  def new
    @agent = Agent.new
  end

  # GET /agents/1/edit
  def edit
  end

  # POST /agents
  # POST /agents.json
  def create
    @agent = Agent.new(agent_params)

    respond_to do |format|
      if @agent.save
        format.html { redirect_to @agent, notice: 'Agent was successfully created.' }
        format.json { render :show, status: :created, location: @agent }
      else
        format.html { render :new }
        format.json { render json: @agent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agents/1
  # PATCH/PUT /agents/1.json
  def update
    respond_to do |format|
      if @agent.update(agent_params)
        format.html { redirect_to @agent, notice: 'Agent was successfully updated.' }
        format.json { render :show, status: :ok, location: @agent }
      else
        format.html { render :edit }
        format.json { render json: @agent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agents/1
  # DELETE /agents/1.json
  def destroy
    @agent.destroy
    respond_to do |format|
      format.html { redirect_to agents_url, notice: 'Agent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agent
      @agent = Agent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agent_params
      params.require(:agent).permit(:agent_id, :name, :call_detail_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/call_details_controller.rb
class CallDetailsController < ApplicationController
  before_action :set_call_detail, only: [:show, :edit, :update, :destroy]

#  def bytime
#      @call_details = CallDetail.where("start_time>= :start_time AND end_time<= :end_time",
#      {start_time: call_detail_start_time, end_time: call_detail_end_time})
#  end

  # GET /call_details
  # GET /call_details.json
  def index
    @call_details = CallDetail.search(params)
    @x_axis = CallDetail.distinct.pluck(:call_id)
    @word_count_bycallid = CallDetail.group(:call_id).count(:word).values
    @chart = LazyHighCharts::HighChart.new('graph') do |f|
      f.title(text: "Count Words in Calls")
      f.xAxis(categories: @x_axis)
      f.series(name: "Word Count", yAxis: 0, data: @word_count_bycallid)

      f.yAxis [
        {title: {text: "Word Count", margin: 70} }
      ]

      f.legend(align: 'right', verticalAlign: 'top', y: 75, x: -50, layout: 'vertical')
      f.chart({defaultSeriesType: "column"})
    end
    #if (params[:start_time]) && (params[:end_time])
      #@call_details = CallDetail.search(params)
    #else
    #@call_details = CallDetail.all
  #end
  end

  # GET /call_details/1
  # GET /call_details/1.json
  def show
  end

  # GET /call_details/new
  def new
    @call_detail = CallDetail.new
  end

  # GET /call_details/1/edit
  def edit
  end

  # POST /call_details
  # POST /call_details.json
  def create
    @call_detail = CallDetail.new(call_detail_params)

    respond_to do |format|
      if @call_detail.save
        format.html { redirect_to @call_detail, notice: 'Call detail was successfully created.' }
        format.json { render :show, status: :created, location: @call_detail }
      else
        format.html { render :new }
        format.json { render json: @call_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /call_details/1
  # PATCH/PUT /call_details/1.json
  def update
    respond_to do |format|
      if @call_detail.update(call_detail_params)
        format.html { redirect_to @call_detail, notice: 'Call detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @call_detail }
      else
        format.html { render :edit }
        format.json { render json: @call_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /call_details/1
  # DELETE /call_details/1.json
  def destroy
    @call_detail.destroy
    respond_to do |format|
      format.html { redirect_to call_details_url, notice: 'Call detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_call_detail
      @call_detail = CallDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def call_detail_params
      params.require(:call_detail).permit(:call_id, :word, :start_time, :end_time)
    end
end

app/controllers/main_page_controller.rb
class MainPageController < ApplicationController
  def call_details
  end

  def agents
  end
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/call_details_helper.rb
module CallDetailsHelper
end

app/helpers/main_page_helper.rb
module MainPageHelper
end

app/views/agents/_form.html.erb
<%= form_with(model: agent, local: true) do |form| %>
  <% if agent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(agent.errors.count, "error") %> prohibited this agent from being saved:</h2>

      <ul>
      <% agent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :agent_id %>
    <%= form.number_field :agent_id, id: :agent_agent_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :agent_name %>
  </div>

  <div class="field">
    <%= form.label :call_detail_id %>
    <%= form.text_field :call_detail_id, id: :agent_call_detail_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/agents/edit.html.erb
<h1>Editing Agent</h1>

<%= render 'form', agent: @agent %>

<%= link_to 'Show', @agent %> |
<%= link_to 'Back', agents_path %>

app/views/agents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Agents</h1>

<table>
  <thead>
    <tr>
      <th>Agent</th>
      <th>Name</th>
      <th>Call detail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @agents.each do |agent| %>
      <tr>
        <td><%= agent.agent_id %></td>
        <td><%= agent.name %></td>
        <td><%= agent.call_detail %></td>
        <td><%= link_to 'Show', agent %></td>
        <td><%= link_to 'Edit', edit_agent_path(agent) %></td>
        <td><%= link_to 'Destroy', agent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p><%= link_to 'New Agent', new_agent_path %></p>
<%= link_to 'Back', main_page_call_details_path %>

app/views/agents/new.html.erb
<h1>New Agent</h1>

<%= render 'form', agent: @agent %>

<%= link_to 'Back', agents_path %>

app/views/agents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Agent:</strong>
  <%= @agent.agent_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @agent.name %>
</p>

<p>
  <strong>Call detail:</strong>
  <%= @agent.call_detail %>
</p>

<%= link_to 'Edit', edit_agent_path(@agent) %> |
<%= link_to 'Back', agents_path %>

app/views/call_details/_bytime_call_details.html.erb
<%= form_tag call_details_path, :method => 'get' do %>
<p>
<%= text_field_tag :start_time, params[:start_time], placeholder: "Start Time" %>
</p>
<p>
<%= text_field_tag :end_time, params[:end_time], placeholder: "End Time" %>
</p>

<%= submit_tag "Search", :name =>nil %>
<% end %>

app/views/call_details/_form.html.erb
<%= form_with(model: call_detail, local: true) do |form| %>
  <% if call_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(call_detail.errors.count, "error") %> prohibited this call_detail from being saved:</h2>

      <ul>
      <% call_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :call_id %>
    <%= form.number_field :call_id, id: :call_detail_call_id %>
  </div>

  <div class="field">
    <%= form.label :word %>
    <%= form.text_field :word, id: :call_detail_word %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.text_field :start_time, id: :call_detail_start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.text_field :end_time, id: :call_detail_end_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/call_details/edit.html.erb
<h1>Editing Call Detail</h1>

<%= render 'form', call_detail: @call_detail %>

<%= link_to 'Show', @call_detail %> |
<%= link_to 'Back', call_details_path %>

app/views/call_details/index.html.erb
<div id="container"></div>
<%= high_chart("container", @chart) %>
<!--<script type="text/javascript" charset="utf-8">
  $(function () {
    new Highcharts.Chart({
      chart: { renderTo: 'word_count_chart' },
      title: { text: 'Word Count by Call ID' },
      xAxis: { type: 'datetime' },
      yAxis: { title: { text: 'Dollars' } },
    series: [{
      name: 'test',
      data: [1, 2, 5, 7, 3]
    }]
    });
  });
</script>-->


<h1>Query Form</h1>

<%= render 'bytime_call_details', call_detail: @call_detail %>

<p id="notice"><%= notice %></p>
<h1>Call Details</h1>

<table>
  <thead>
    <tr>
      <th>Call ID</th>
      <th>Word</th>
      <th>Start time</th>
      <th>End time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @call_details.each do |call_detail| %>
      <tr>
        <td><%= call_detail.call_id %></td>
        <td><%= call_detail.word %></td>
        <td><%= call_detail.start_time %></td>
        <td><%= call_detail.end_time %></td>
        <td><%= link_to 'Show', call_detail %></td>
        <td><%= link_to 'Edit', edit_call_detail_path(call_detail) %></td>
        <td><%= link_to 'Destroy', call_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p><%= link_to 'New Call Detail', new_call_detail_path %></p>
<%= link_to 'Back', main_page_call_details_path %>

app/views/call_details/new.html.erb
<h1>New Call Detail</h1>

<%= render 'form', call_detail: @call_detail %>

<%= link_to 'Back', call_details_path %>

app/views/call_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Call:</strong>
  <%= @call_detail.call_id %>
</p>

<p>
  <strong>Word:</strong>
  <%= @call_detail.word %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @call_detail.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @call_detail.end_time %>
</p>

<%= link_to 'Edit', edit_call_detail_path(@call_detail) %> |
<%= link_to 'Back', call_details_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TianaV0</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main_page/agents.html.erb
<h1>MainPage#agents</h1>
<p>Find me in app/views/main_page/agents.html.erb</p>

app/views/main_page/call_details.html.erb
<h1>Demo T-i-(ana) Version 0</h1>
  <p><%= link_to 'Phrase Cloud', call_details_path %></p>
  <%= link_to 'Agent Score', agents_path %>